<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ApplePeripheralsSetup</AssemblyName>
    <RootNamespace>ApplePeripherals.Setup</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.3.9-usb-local</Version>
  </PropertyGroup>

  <ItemGroup Condition="'$(PayloadZip)' != ''">
    <EmbeddedResource Include="$(PayloadZip)" LogicalName="ApplePeripheralsPayload.zip" />
  </ItemGroup>

  <ItemGroup Condition="'$(DriverZip)' != ''">
    <EmbeddedResource Include="$(DriverZip)" LogicalName="MagicTrackpad2ForWindows-MSSigned.zip" />
  </ItemGroup>

  <ItemGroup Condition="'$(KeyboardDriverZip)' != ''">
    <EmbeddedResource Include="$(KeyboardDriverZip)" LogicalName="AppleKeyboardFilterDriver.zip" />
  </ItemGroup>
</Project>
